### ISSUE TITLE
code not found: 0xd0

### ISSUE THREAD

**Issue by khcnz** [scottyphillips/pychonet#1]
I'm getting a code not found error on the console 0xd0 is missing. I'm guessing it's this one? 
![image](https://user-images.githubusercontent.com/130233/124590815-aee7c500-deaf-11eb-8e56-cf505dcf6c60.png)

**Comment by scottyphillips** [comment]
What command were you running in the console?

**Comment by khcnz** [comment]
The error prints to the console just when instantiating the object
aircon = echonet.HomeAirConditioner("192.168.4.34")

From the spec i've got 0xD0 exists on 
![image](https://user-images.githubusercontent.com/130233/124596173-130d8780-deb6-11eb-805b-167c14936dfd.png)
but not the Home Air Conditioner 0x30..? 

I've mapped it but don't get any bytes back on this one. Hrrrrm.

**Comment by scottyphillips** [comment]
When the object is instantiated it will build a property map - the idea is that these don’t change so no need to continue to poll the API after. I think this appears to be a rogue attribute that according to the spec shouldn’t belong to the home air conditioner class?

**Comment by khcnz** [comment]
Seems to be _I think_  perhaps the best fix here would be to just comment the print out? I'd wager other people might have the same issue with this or other opcodes with other devices

**Comment by scottyphillips** [comment]
Have you run discover and confirmed it’s indeed a home aircon?

**Comment by khcnz** [comment]
HA! I think you might be right on this one.. Discover hadn't worked for me in the past (returns nothing) and I had just assumed it was some oddity of my environment. I think you might be right that maybe it's returning a different class type. I'm not at the location with the heatpumps and don't think multicast works over VPN but will confirm this weekend.

**Comment by scottyphillips** [comment]
The Multicast function doesn’t seem to work on raspbian but works on MacOS. You can run discover against the IP address now and it should work as unicast

Scott

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gvswastaken** [comment]
In a local branch I actually commented out the "code not found" message so the library is quiet to at least stdout.

**Comment by khcnz** [comment]
Oh and it seems my device is a home air conditioner so it must just be supporting a code that it shouldn't be..
 [{'netaddr': '192.168.x.x', 'eojgc': 1, 'eojcc': 48, 'eojci': 1, 'group': 'Air conditioner-related device group', 'code': 'Home air conditioner'}]}

**Comment by gvswastaken** [comment]
I also have some devices using reserved codes with reserved attributes (specifically Panasonic Smart Cosmo and Power Station S+) that do not seem to be documented anywhere, unfortunately it does not seem uncommon.
