### ISSUE TITLE
Confused about versioning

### ISSUE THREAD

**Issue by ammgws** [scottyphillips/pychonet#12]
The badge in the README shows the latest release as 1.0.8

However, the current release on PyPi is 2.0.12 (taken from `setup.py` since it's pointing to the async branch)

On GitHub, the latest git tag is 2.0.11, but I guess GitHub only considers the master branch so the latest version is shown as 1.0.8.

Is it just in a transition period where the async branch will soon be merged into master?

**Comment by khcnz** [comment]
This asynchonet branch is the latest and the one that is used by home assistant 

It was experimental but I think the intention is to merge this back to master soon as it's not the one being used.

**Comment by scottyphillips** [comment]
Yes it was a bit of a mess on my part but I wanted to make sure the asyncio code worked ok... Version 2.0.13 is now the master.
