### ISSUE TITLE
Behaviour change between 2.6.1 and 2.6.2

### ISSUE THREAD

**Issue by josh-shaw-dev** [scottyphillips/pychonet#75]
Can someone confirm the behavior that I am meant to see between 2.6.1 and 2.6.2

I'm seeing a 30 second delay for these requests in 2.6.2.

Is this to be  expected? as I'm trying to diagnose the home assistant component dropping out

2.6.1 - notice the speed is fast 0.1 of a second per request
```python
pip install --force-reinstall -v "pychonet==2.6.1"

python aircon_test.py "192.168.70.18"
Took  0.100752 seconds. Is on =  b'1'
Took  0.100917 seconds. Is on =  b'1'
Took  0.100632 seconds. Is on =  b'1'
Took  0.100575 seconds. Is on =  b'1'
Took  0.100708 seconds. Is on =  b'1'
Took  0.101072 seconds. Is on =  b'1'
Took  0.100979 seconds. Is on =  b'1'
Took  0.100879 seconds. Is on =  b'1'
```
2.6.2 - Taking 30 seconds per request
```python
pip install --force-reinstall -v "pychonet==2.6.2"

python aircon_test.py "192.168.70.18"
Took  30.056935 seconds. Is on =  False
Took  30.057373 seconds. Is on =  False
Took  30.057197 seconds. Is on =  False
Took  30.057009 seconds. Is on =  False

```

Test script taken from https://github.com/scottyphillips/pychonet/blob/master/example_async.py and modified to just get the aircon state as fast as possible
```python
import asyncio
import datetime
import sys

from pychonet.lib.udpserver import UDPServer
from pychonet import ECHONETAPIClient as api
from pychonet import HomeAirConditioner

async def main(argv):
    udp = UDPServer()
    loop = asyncio.get_event_loop()
    udp.run("0.0.0.0", 3610, loop=loop)
    server = api(udp)
    server._debug_flag = False
    server._message_timeout = 300
    target = argv[1]

    await server.discover(target)
    # Timeout after 3 seconds
    for x in range(0, 300):
        await asyncio.sleep(0.01)
        if "discovered" in list(server._state[target]):
            break

    aircon = HomeAirConditioner(target, server)
    while True:
        beforeGet = datetime.datetime.now()
        res = await aircon.getOperationalStatus()
        diff = (datetime.datetime.now() - beforeGet).total_seconds()  
        print("Took ", diff, "seconds. Is on = ", res)

if __name__ == "__main__":
    asyncio.run(main(sys.argv))
```

**Comment by scottyphillips** [comment]
Yes I can confirm the same behavior.

**Comment by scottyphillips** [comment]
@josh-shaw-dev my environment is a mess as my main computer died a few weeks ago so I am not able to publish a new release. but I think the above will resolve the issue. There was a list for tracking the number of outstanding messages that was being instantiated, and then values get added or removed as needed, and 'None' is very much different to '{}' in python land.

**Comment by josh-shaw-dev** [comment]
@scottyphillips That seems to have it going the fast speed like 2.6.1

Occasionally when I run the script I am seeing a key error like its not being discovered to start with though not sure if that is related or just a failure when trying to discover the target to begin with. I assume its the latter

```
  File "/home/yes/Dev/aircon_test/pychonet/aircon_test.py", line 33, in <module>
    asyncio.run(main(sys.argv))
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/yes/Dev/aircon_test/pychonet/aircon_test.py", line 25, in main
    aircon = HomeAirConditioner(target, server)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yes/Dev/aircon_test/pychonet/pychonet/HomeAirConditioner.py", line 287, in __init__
    EchonetInstance.__init__(
  File "/home/yes/Dev/aircon_test/pychonet/pychonet/EchonetInstance.py", line 56, in __init__
    self._epc_data = self._api._state[self._host]["instances"][self._eojgc][
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 1

```

**Comment by scottyphillips** [comment]
Yes that looks like a missed discovery to me.

**Comment by josh-shaw-dev** [comment]
> 2.6.2 had a bug in decrementing waiting[host], which could cause it to wait forever, but that was fixed in [4cf0747](https://github.com/scottyphillips/pychonet/commit/4cf0747a027871b3fb6a5edb5f2c34a434ae836f). It's been fixed in 2.6.7 and later, so could you check that in later versions as well?

I can confirm that the slow behavior exists from version 2.6.2 and up, I double checked 2.6.8 and 2.6.13 (latest) and the slowness is still there.

Also cloned the repo and checked against c361e6d (before Scotts fix)  and it was still slow

Scotts fix in 19e56c3 has fixed the delay and speed is back to 2.6.1 level

**Comment by scottyphillips** [comment]
Problem line is this:

`if self._message_list.get(tx_tid) is None:`

When testing `self._message_list.get ` it is only None until the list is instantiated. An empty list is not None, rather {}, so it never fired again after the very first packet.

**Comment by josh-shaw-dev** [comment]
> So, having considered @nao-pon response this morning, the problem lies not with my initial fix yesterday but earlier with the processing of the ECHONET lite messages.
> 
> L.211 in echonetMessageReceived() **is supposed to** delete tid_data from self._message_list[tx_tid]. But this is clearly not happening.

I tried some more debugging at lunch, I can see it send and recieve the first udp packet (I think its the discover part).

It appears to send the second message however not recieve a a response to it, I can see it awaiting in the udpserver to recieve

I will confirm what is being sent over the network with wireshark later on tonight to see if its actually getting anything back or its a fault in the code somewhere

**Comment by josh-shaw-dev** [comment]
Wireshark dumps attached

On the surface it looks as what is being sent to the echonet device has changed for at least the getOperationalStatus command from the script above and its no longer getting a reply from the echonet device

Scotts change allowed it to send lots of requests though nothing was received after what I assume is the discover, you can see that in the ScottsFix dump

I can only guess that since the request packet has changed the echonet device isnt replying as its not valid?

I'm not going to pretend I know what the data in the dumps mean in terms of echonet lite protocol so hopefully this give you some idea on what might be happening

Taken from version 2.6.1
 data is 14 bytes
```
3	0.211491453	192.168.40.100	192.168.70.18	UDP	56	3610 → 3610 Len=14

Hex
10 81 00 02 05 ff 01 01 30 01 62 01 80 00
```

Taken from Scotts Fix
data is only 12 bytes
```
3	0.110755611	192.168.40.100	192.168.70.18	UDP	54	3610 → 3610 Len=12

10 81 00 02 05 ff 01 01 30 01 62 00
```

Taken from head of master
data is only 12 bytes
```
3	0.110872015	192.168.40.100	192.168.70.18	UDP	54	3610 → 3610 Len=12

Hex
10 81 00 02 05 ff 01 01 30 01 62 00
```
[Dumps.zip](https://github.com/user-attachments/files/17302321/Dumps.zip)

**Comment by scottyphillips** [comment]
Okay, after more testing with your test script it's imperative to perfom `await aircon.getAllPropertyMaps()` after defining HomeAirConditioner because that correctly populates the device table with the expected EPC codes. 

With this line included it behaves normally even on the latest code and is quick to respond. I expect there is probably a poorly handled exception in there when processing the packet with newer versions of the code.

**Comment by josh-shaw-dev** [comment]
Damn so the thing that changed it's not doing auto property mapping anymore. 

Thanks for looking into it with me. I'll go back to the drawing board and see if I can figure out the issue I'm seeing in the home assistant component
